"""add news_images table

Revision ID: 23ad3b10f1ce
Revises: 468f5e0965fa
Create Date: 2026-09-28 12:06:14.310612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ad3b10f1ce'
down_revision = '468f5e0965fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'news_posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('news_post_id')

    with op.batch_alter_table('news_posts', schema=None) as batch_op:
        batch_op.drop_column('external_url')
        batch_op.drop_column('is_flash')
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=False))
        batch_op.add_column(sa.Column('is_flash', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False))
        batch_op.add_column(sa.Column('external_url', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('news_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_post_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'news_posts', ['news_post_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
