"""add news_posts table

Revision ID: 468f5e0965fa
Revises: 
Create Date: 2026-09-26 18:43:45.540453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468f5e0965fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('lga',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('business_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('complaint_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('complaint_details',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('evidence',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(), server_default=sa.text("'Pending'"), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('evidence',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('complaint_details',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('complaint_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('business_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('lga',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('news_posts')
    # ### end Alembic commands ###
